# Generated by Django 5.1.2 on 2024-12-21 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('id_game', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('game', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=50)),
                ('away', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('league', models.CharField(max_length=50)),
                ('hour_game', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=10)),
                ('who_scored', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_points', models.IntegerField(blank=True, null=True)),
                ('home_goal_scored', models.IntegerField(blank=True, null=True)),
                ('home_goal_conceded', models.IntegerField(blank=True, null=True)),
                ('away_points', models.IntegerField(blank=True, null=True)),
                ('away_goal_scored', models.IntegerField(blank=True, null=True)),
                ('away_goal_conceded', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScoreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_average', models.FloatField(blank=True, null=True)),
                ('away_score_average', models.FloatField(blank=True, null=True)),
                ('home_scoring_rate', models.CharField(max_length=10)),
                ('away_scoring_rate', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_score_stats', to='api.game')),
            ],
        ),
    ]
